export const rules: string[] = [
  "Lütfen emniyet kemerinizi takmayı unutmayınız!",
  "Hız sınırlarına uyarak güvenliğinizi sağlayınız.",
  "Alkollü araç kullanmayınız!",
  "Trafik ışıklarına ve işaretlerine dikkat ediniz.",
  "Yaya geçitlerinde yayalara öncelik veriniz.",
  "Araç kullanırken telefon kullanmaktan kaçınınız.",
  "Trafikte sabırlı ve saygılı olunuz.",
  "Takip mesafesini koruyunuz!",
  "Park yasaklarına dikkat ediniz.",
  "Geçiş üstünlüğüne sahip araçlara yol veriniz.",
  "Çocuklar için uygun araç koltuğu kullanınız.",
  "Lastik hava basıncınızı düzenli olarak kontrol ediniz.",
  "Sisli havalarda sis farlarını kullanmayı unutmayınız.",
  "Aracınızın bakımını zamanında yaptırınız.",
  "Trafik kuralları hayat kurtarır, lütfen uyunuz!",
];
